#!/usr/bin/env bash

if [ -f "env/docker.env" ]; then
    source ./env/docker.env
fi

# Set environment variables for compose
export APP_ENV=${SYMFONY_APP_ENV:-dev}
export APP_PORT=${SYMFONY_APP_PORT:-80}
export ES_PORT=${SYMFONY_ES_PORT:-9200}
export APP_DOMAIN=${SYMFONY_APP_DOMAIN:-dev.symfony}

echo -e "\e[96m ENV=$APP_ENV; DOMAIN=$APP_DOMAIN \e[0m"

if [ "$APP_ENV" == "prod" ]; then
    COMPOSE_FILE="-f docker-compose.yml"
else
    COMPOSE_FILE="-f docker-compose.yml -f docker-compose-dev.yml"
    export DB_PORT=${SYMFONY_DB_PORT:-3306}
fi

if [ $# -gt 0 ]; then
    docker-compose $COMPOSE_FILE "$@"
else
    docker-compose $COMPOSE_FILE ps
fi
