version: '2'
services:
  code:
    container_name: code
    build: images/code
    volumes:
      - "../project:/var/www"

  fpm:
    container_name: fpm
    build: images/fpm
    working_dir: /var/www
    volumes_from:
      - code
    env_file:
      - ./env/symfony.env
    restart: unless-stopped

  cli:
    container_name: cli
    build: images/cli
    working_dir: /var/www
    tty: true
    volumes_from:
      - code
    volumes:
      - "./.composer:/root/.composer"
    environment:
      COMPOSER_ALLOW_SUPERUSER: 1
    env_file:
      - ./env/symfony.env
      
  nginx:
    container_name: nginx
    build:
      context: images/nginx
      args:
        ENV: ${APP_ENV}
        DOMAIN: ${APP_DOMAIN}
        USER: ${BASE_AUTH_USER}
        PASSWORD: ${BASE_AUTH_PASSWORD}
    working_dir: /var/www
    volumes_from:
      - code
    ports:
      - "${APP_PORT}:80"
    volumes:
      - "./volumes/nginx/:/var/log/nginx"
    restart: unless-stopped

  es:
    container_name: es
    build: images/es
    ports:
      - "${ES_PORT}:9200"
    volumes:
      - "./volumes/es/:/usr/share/elasticsearch/data"
      - "./volumes/es/logs/:/usr/share/elasticsearch/log"
